on:
  push:
    branches:
      - staging

jobs:
  test-version-refs:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Push to main/Main
      - name: Push to main 
        if: success()
        run: |
          # Configure git
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config pull.rebase false  # Explicitly set the merge strategy for pull
     
          git remote add gh-token "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"          
          
          # Fetch all branches
          git fetch --all

          # Checkout the 'main' branch from the specified remote (e.g., 'origin/main')
          git checkout -b main origin/main  # Change 'origin' to the appropriate remote if necessary

          # Pull changes from staging, resolving conflicts by favoring changes from staging
          git pull origin staging --allow-unrelated-histories -X theirs

          # Add all changes (including file renames)
          git add -A
            
          # Create a squashed commit
          commit_message="Squash-like merge from staging: $(date +%Y-%m-%d)"
          git commit -m "$commit_message"

          # Push the squashed commit to main
          git push gh-token HEAD:main 

          # Go back to staging and merge the changes to keep it up to date
          git checkout gh-token staging
          git merge gh-token main
          git push gh-token staging