on:
  push:
    branches:
      - staging

jobs:
  replace-main-with-staging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Remove all files in main
        run: |
          sudo rm -rf *

      - name: Clone staging branch into temp directory
        run: |
          repoStr=${{ github.repository }}
          repoName=${repoStr#*/}
          git clone --single-branch --branch staging https://www.github.com/${{ github.actor }}/${repoName}.git temp

      - name: Sync cloned files to main directory, excluding .git
        run: |
          rsync -av --exclude='.git' temp/ ./
          rsync -av temp/.github/ .github/
          rm -rf temp

      - name: Add all changes and commit
        run: |
          git add .
          git commit -m "Replace main contents with staging"
          git push origin main
